---
title: "Xochitl Medina"
---


## [Education]()



•Lincoln Technical Academy, Delta Community College 	**(2016–2018)**

    Health care industry training and experience

•University of California Santa Barbara 	**(2018–Present)**
   
     B.A. in Environmental Studies and Geographic Information Systems

## [Experience]()



•Career and Technical Education Intern, 
*Sutter Gould Medical Foundation, Stockton, CA*	**(September 2017–May 2018)**

    •	Organized and prepared examination rooms

    •	Conducted confirmation calls with patients

    •	Customer service


•Coordinator (3×),
*American Red Cross Blood Drive, Stockton, CA*	**(Sep. 2017, Dec. 2017, April 2018)**

    •	Coordinated the flow of incoming donors

    •	Directed donors to proper stations

    •	Event planning


•Residence Hall Desk Attendant,             	*University of California Santa Barbara, Manzanita Hall* 	**(October 2019 – March 2020)**

    •	Scheduled meetings for UCSB staff

    •	Organized and managed room keys for hall residents

    •	Greeted and assisted all desk visitors



